### ISSUE TITLE
API

### ISSUE THREAD

**Issue by nohgijin** [siliconValleyTeamA/client#50]
## 에러처리
200
404
500 이상

# ⭐️Log In
### Endpoint

**`POST`** `/api/login`

### Body

| Property   | Type     | Description   |
| ---------- | -------- | ------------- |
| `id`    | `string` | User Github ID       |

language는 브라우저단에 저장
따라서 수정도 필요없음. 브라우저에서 수정하면됨.

## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `success` | `boolean` | Whether signed in or not |

# ⭐️Log Out
### Endpoint

**`POST`** `/api/logout`

## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `success` | `boolean` | Whether signed in or not |

# ⭐️Get Jjim List
### Endpoint

**`GET`** `/api/jjims`

## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `jjimList` | `Jjim[]` | Get Jjim list  |

# ⭐️Get a History Data
### Endpoint

**`GET`** `/api/history`

## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `historyList` | `History[]` | Get History list  |

# ⭐️Get a Point
### Endpoint

**`GET`** `/api/point`

## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `point` | `int` | Get point information  |

# ⭐️Modify a Point
### Endpoint

**`PUT`** `/api/point`

### Body

| Property   | Type     | Description   |
| ---------- | -------- | ------------- |
| `point`       | `int` |    amount of point    |

## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `success` | `boolean` | Whether modified or not |

**Comment by YeonJeongLee00** [comment]
# ⭐️Get ProjectList 
## Request

### Endpoint

**`GET`** `/api/category/:categoryId`


## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `projectList` | `Project[]` | Get Project list |

# ⭐️Get CategoryList 
## Request

### Endpoint

**`GET`** `/api/category`


## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `categoryList` | `Category[]` | Get Category list |

**Comment by dbckdgjs369** [comment]
# ⭐️PopularPage
## Request

### Get Endpoint

**`GET`** `/api/popular`

## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `popularProjectList` | `PopularList[]` | Popular Projects List |


# ⭐️Project Description Page
## Request

### Endpoint

**`GET`** `/api/project/:projectId`

## Response

| Property  | Type      | Description              |
| --------- | --------- | ------------------------ |
| `projectId` | `int` | Project’s Unique Id |
| `picture` | `string` | Project’s Picture |
| `detail` | `string` | Project’s Description |
